AllCops:
  TargetRubyVersion: 2.7
  Include:
    - '**/*.rake'
    - '**/*.rb'
    - '**/config.ru'
    - '**/Rakefile'
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'script/**/*'

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*.rb'
    - 'app/helpers/**/*.rb'
    - 'app/models/**/*.rb'
    - 'config/**/*.rb'
    - 'db/migrate/*.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/support/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Layout/LineLength:
  Max: 100
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/seeds/*.rb'
    - 'config/**/*.rb'
    - 'Gemfile'
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/MultilineAssignmentLayout:
  Enabled: true
Layout/DotPosition:
  EnforcedStyle: trailing

Style/OptionHash:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
  # waiting on https://github.com/rrosenblum/rubocop/commit/0c7f91b0abeb2dad305edfa301366b504bb7b734
Style/ClassAndModuleChildren:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'Gemfile'

Bundler/OrderedGems:
  Enabled: false
