blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/CMDBrew/adminterface/discussions
    about: Suggest an idea to improve Adminterface in our GitHub Discussions
  - name: Need Help?
    url: https://github.com/CMDBrew/adminterface/discussions
    about: Please ask Adminterface related questions in our GitHub Discussions
