module.exports = {
  community: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      href: 'https://github.com/CMDBrew/active_admin_bootstrap/blob/master/CHANGELOG.md',
      label: 'Changelog',
    },
    {
      type: 'link',
      href: 'https://github.com/CMDBrew/active_admin_bootstrap/discussions',
      label: 'Feedback',
    }
  ],
};
