name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler: default
          bundler-cache: true

      - name: Run linters
        run: |
          bundle exec rails prepare_assets
          yarn lint

  sqlite:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        ruby: ['2.7', '3.0']
        gemfile:
          - rails_6_0
          - rails_6_1
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true

      - name: Run tests
        env:
          DATABASE_URL: "sqlite3:active_admin_bootstrap_test"
          RAILS_ENV: test
          NODE_ENV: test
        run: |
          bundle exec rails prepare_assets
          bundle exec rails db:test:prepare
          bundle exec rails test

  mysql:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        ruby: ['2.7', '3.0']
        gemfile:
          - rails_6_0
          - rails_6_1
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true

      - name: Run tests
        env:
          DATABASE_URL: mysql2://root:password@127.0.0.1:3306/test
          RAILS_ENV: test
          NODE_ENV: test
        run: |
          bundle exec rails prepare_assets
          bundle exec rails db:test:prepare
          bundle exec rails test

  postgres:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0']
        gemfile:
          - rails_6_0
          - rails_6_1
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports: ['5432:5432']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test
          RAILS_ENV: test
          NODE_ENV: test
        run: |
          bundle exec rails prepare_assets
          bundle exec rails db:test:prepare
          bundle exec rails test
