---
name: Pre-Release

on:
  push:
    branches:
      - main

jobs:
  npm:
    name: Publish NPM Package on Github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler: default
          bundler-cache: true
      - name: Set up NPM
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
      - run: |
          gem install gem-release
          GEM_VERSION=$(gem bump -v patch --pretend --no-commit | awk '{ print $4 }')
          npm version $GEM_VERSION-rc$GITHUB_RUN_ID --no-git-tag-version
      - run: yarn install
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  ruby:
    name: Publish Ruby gem on Github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler: default
          bundler-cache: true
      - run: |
          gem install gem-release
          GEM_VERSION=$(gem bump -v patch --pretend --no-commit | awk '{ print $4 }')
          gem bump -v $GEM_VERSION.rc$GITHUB_RUN_ID --no-commit
      - name: Publish to GitHub Ruby Gem
        uses: jstastny/publish-gem-to-github@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: cmdbrew

  delete_previous_rc_versions:
    needs: [npm, ruby]
    name: Delete previous release candidates
    runs-on: ubuntu-latest
    steps:
      - uses: smartsquaregmbh/delete-old-packages@v0.3.1
        with:
          keep: 2
          version-pattern: "^\\d+\\.\\d+\\.\\d+(-|\\.)rc\\d+$"
          dry-run: false
          names: |
            adminterface
