---
name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            LICENSE.md

  npm:
    name: Publish NPM package on Github
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  ruby:
    name: Publish Ruby gem on Github
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - name: Publish to GitHub Ruby Gem
        uses: jstastny/publish-gem-to-github@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: cmdbrew

  delete_rc_versions:
    needs: [npm, ruby]
    name: Delete release candidates for the current version
    runs-on: ubuntu-latest
    steps:
      - id: get-version
        run: |
          version=$(echo ${GITHUB_REF#refs/*/} | cut -dv -f2)
          echo "current release version is $version"
          echo "::set-output name=version::$version"
      - uses: smartsquaregmbh/delete-old-packages@v0.3.1
        with:
          keep: 0
          version-pattern: "${{ steps.get-version.outputs.version }}(-|\\.)rc\\d+$"
          dry-run: true
          names: |
            adminterface
